// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: session.proto

package sessionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MentorshipService_CreateSlot_FullMethodName            = "/MentorshipService/CreateSlot"
	MentorshipService_GetSlot_FullMethodName               = "/MentorshipService/GetSlot"
	MentorshipService_UpdateSlot_FullMethodName            = "/MentorshipService/UpdateSlot"
	MentorshipService_DeleteSlot_FullMethodName            = "/MentorshipService/DeleteSlot"
	MentorshipService_CreateSession_FullMethodName         = "/MentorshipService/CreateSession"
	MentorshipService_GetSession_FullMethodName            = "/MentorshipService/GetSession"
	MentorshipService_UpdateSession_FullMethodName         = "/MentorshipService/UpdateSession"
	MentorshipService_DeleteSession_FullMethodName         = "/MentorshipService/DeleteSession"
	MentorshipService_ListSessionsByMentor_FullMethodName  = "/MentorshipService/ListSessionsByMentor"
	MentorshipService_ListSessionsByStudent_FullMethodName = "/MentorshipService/ListSessionsByStudent"
	MentorshipService_UpdateSlotStatus_FullMethodName      = "/MentorshipService/UpdateSlotStatus"
	MentorshipService_RateSession_FullMethodName           = "/MentorshipService/RateSession"
	MentorshipService_GetSlotsByMentor_FullMethodName      = "/MentorshipService/GetSlotsByMentor"
)

// MentorshipServiceClient is the client API for MentorshipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MentorshipServiceClient interface {
	CreateSlot(ctx context.Context, in *CreateSlotRequest, opts ...grpc.CallOption) (*CreateSlotResponse, error)
	GetSlot(ctx context.Context, in *GetSlotRequest, opts ...grpc.CallOption) (*GetSlotResponse, error)
	UpdateSlot(ctx context.Context, in *UpdateSlotRequest, opts ...grpc.CallOption) (*UpdateSlotResponse, error)
	DeleteSlot(ctx context.Context, in *DeleteSlotRequest, opts ...grpc.CallOption) (*DeleteSlotResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	ListSessionsByMentor(ctx context.Context, in *ListSessionsByMentorRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	ListSessionsByStudent(ctx context.Context, in *ListSessionsByStudentRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	UpdateSlotStatus(ctx context.Context, in *UpdateSlotStatusRequest, opts ...grpc.CallOption) (*UpdateSlotStatusResponse, error)
	RateSession(ctx context.Context, in *RateSessionRequest, opts ...grpc.CallOption) (*RateSessionResponse, error)
	GetSlotsByMentor(ctx context.Context, in *GetSlotsByMentorRequest, opts ...grpc.CallOption) (*GetSlotsByMentorResponse, error)
}

type mentorshipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMentorshipServiceClient(cc grpc.ClientConnInterface) MentorshipServiceClient {
	return &mentorshipServiceClient{cc}
}

func (c *mentorshipServiceClient) CreateSlot(ctx context.Context, in *CreateSlotRequest, opts ...grpc.CallOption) (*CreateSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSlotResponse)
	err := c.cc.Invoke(ctx, MentorshipService_CreateSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) GetSlot(ctx context.Context, in *GetSlotRequest, opts ...grpc.CallOption) (*GetSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSlotResponse)
	err := c.cc.Invoke(ctx, MentorshipService_GetSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) UpdateSlot(ctx context.Context, in *UpdateSlotRequest, opts ...grpc.CallOption) (*UpdateSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSlotResponse)
	err := c.cc.Invoke(ctx, MentorshipService_UpdateSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) DeleteSlot(ctx context.Context, in *DeleteSlotRequest, opts ...grpc.CallOption) (*DeleteSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSlotResponse)
	err := c.cc.Invoke(ctx, MentorshipService_DeleteSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, MentorshipService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, MentorshipService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionResponse)
	err := c.cc.Invoke(ctx, MentorshipService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, MentorshipService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) ListSessionsByMentor(ctx context.Context, in *ListSessionsByMentorRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, MentorshipService_ListSessionsByMentor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) ListSessionsByStudent(ctx context.Context, in *ListSessionsByStudentRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, MentorshipService_ListSessionsByStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) UpdateSlotStatus(ctx context.Context, in *UpdateSlotStatusRequest, opts ...grpc.CallOption) (*UpdateSlotStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSlotStatusResponse)
	err := c.cc.Invoke(ctx, MentorshipService_UpdateSlotStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) RateSession(ctx context.Context, in *RateSessionRequest, opts ...grpc.CallOption) (*RateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateSessionResponse)
	err := c.cc.Invoke(ctx, MentorshipService_RateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mentorshipServiceClient) GetSlotsByMentor(ctx context.Context, in *GetSlotsByMentorRequest, opts ...grpc.CallOption) (*GetSlotsByMentorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSlotsByMentorResponse)
	err := c.cc.Invoke(ctx, MentorshipService_GetSlotsByMentor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MentorshipServiceServer is the server API for MentorshipService service.
// All implementations must embed UnimplementedMentorshipServiceServer
// for forward compatibility.
type MentorshipServiceServer interface {
	CreateSlot(context.Context, *CreateSlotRequest) (*CreateSlotResponse, error)
	GetSlot(context.Context, *GetSlotRequest) (*GetSlotResponse, error)
	UpdateSlot(context.Context, *UpdateSlotRequest) (*UpdateSlotResponse, error)
	DeleteSlot(context.Context, *DeleteSlotRequest) (*DeleteSlotResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	ListSessionsByMentor(context.Context, *ListSessionsByMentorRequest) (*ListSessionsResponse, error)
	ListSessionsByStudent(context.Context, *ListSessionsByStudentRequest) (*ListSessionsResponse, error)
	UpdateSlotStatus(context.Context, *UpdateSlotStatusRequest) (*UpdateSlotStatusResponse, error)
	RateSession(context.Context, *RateSessionRequest) (*RateSessionResponse, error)
	GetSlotsByMentor(context.Context, *GetSlotsByMentorRequest) (*GetSlotsByMentorResponse, error)
	mustEmbedUnimplementedMentorshipServiceServer()
}

// UnimplementedMentorshipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMentorshipServiceServer struct{}

func (UnimplementedMentorshipServiceServer) CreateSlot(context.Context, *CreateSlotRequest) (*CreateSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSlot not implemented")
}
func (UnimplementedMentorshipServiceServer) GetSlot(context.Context, *GetSlotRequest) (*GetSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlot not implemented")
}
func (UnimplementedMentorshipServiceServer) UpdateSlot(context.Context, *UpdateSlotRequest) (*UpdateSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSlot not implemented")
}
func (UnimplementedMentorshipServiceServer) DeleteSlot(context.Context, *DeleteSlotRequest) (*DeleteSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSlot not implemented")
}
func (UnimplementedMentorshipServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedMentorshipServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedMentorshipServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedMentorshipServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedMentorshipServiceServer) ListSessionsByMentor(context.Context, *ListSessionsByMentorRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessionsByMentor not implemented")
}
func (UnimplementedMentorshipServiceServer) ListSessionsByStudent(context.Context, *ListSessionsByStudentRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessionsByStudent not implemented")
}
func (UnimplementedMentorshipServiceServer) UpdateSlotStatus(context.Context, *UpdateSlotStatusRequest) (*UpdateSlotStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSlotStatus not implemented")
}
func (UnimplementedMentorshipServiceServer) RateSession(context.Context, *RateSessionRequest) (*RateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateSession not implemented")
}
func (UnimplementedMentorshipServiceServer) GetSlotsByMentor(context.Context, *GetSlotsByMentorRequest) (*GetSlotsByMentorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlotsByMentor not implemented")
}
func (UnimplementedMentorshipServiceServer) mustEmbedUnimplementedMentorshipServiceServer() {}
func (UnimplementedMentorshipServiceServer) testEmbeddedByValue()                           {}

// UnsafeMentorshipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MentorshipServiceServer will
// result in compilation errors.
type UnsafeMentorshipServiceServer interface {
	mustEmbedUnimplementedMentorshipServiceServer()
}

func RegisterMentorshipServiceServer(s grpc.ServiceRegistrar, srv MentorshipServiceServer) {
	// If the following call pancis, it indicates UnimplementedMentorshipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MentorshipService_ServiceDesc, srv)
}

func _MentorshipService_CreateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).CreateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_CreateSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).CreateSlot(ctx, req.(*CreateSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_GetSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).GetSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_GetSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).GetSlot(ctx, req.(*GetSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_UpdateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).UpdateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_UpdateSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).UpdateSlot(ctx, req.(*UpdateSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_DeleteSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).DeleteSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_DeleteSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).DeleteSlot(ctx, req.(*DeleteSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_ListSessionsByMentor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsByMentorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).ListSessionsByMentor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_ListSessionsByMentor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).ListSessionsByMentor(ctx, req.(*ListSessionsByMentorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_ListSessionsByStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsByStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).ListSessionsByStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_ListSessionsByStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).ListSessionsByStudent(ctx, req.(*ListSessionsByStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_UpdateSlotStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSlotStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).UpdateSlotStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_UpdateSlotStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).UpdateSlotStatus(ctx, req.(*UpdateSlotStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_RateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).RateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_RateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).RateSession(ctx, req.(*RateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MentorshipService_GetSlotsByMentor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlotsByMentorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MentorshipServiceServer).GetSlotsByMentor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MentorshipService_GetSlotsByMentor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MentorshipServiceServer).GetSlotsByMentor(ctx, req.(*GetSlotsByMentorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MentorshipService_ServiceDesc is the grpc.ServiceDesc for MentorshipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MentorshipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MentorshipService",
	HandlerType: (*MentorshipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSlot",
			Handler:    _MentorshipService_CreateSlot_Handler,
		},
		{
			MethodName: "GetSlot",
			Handler:    _MentorshipService_GetSlot_Handler,
		},
		{
			MethodName: "UpdateSlot",
			Handler:    _MentorshipService_UpdateSlot_Handler,
		},
		{
			MethodName: "DeleteSlot",
			Handler:    _MentorshipService_DeleteSlot_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _MentorshipService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _MentorshipService_GetSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _MentorshipService_UpdateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _MentorshipService_DeleteSession_Handler,
		},
		{
			MethodName: "ListSessionsByMentor",
			Handler:    _MentorshipService_ListSessionsByMentor_Handler,
		},
		{
			MethodName: "ListSessionsByStudent",
			Handler:    _MentorshipService_ListSessionsByStudent_Handler,
		},
		{
			MethodName: "UpdateSlotStatus",
			Handler:    _MentorshipService_UpdateSlotStatus_Handler,
		},
		{
			MethodName: "RateSession",
			Handler:    _MentorshipService_RateSession_Handler,
		},
		{
			MethodName: "GetSlotsByMentor",
			Handler:    _MentorshipService_GetSlotsByMentor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}
