syntax = "proto3";

package chatv1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/Sergey-1214/contracts_mentors/chat/v1;chatv1";

service ChatService {
  rpc CreateChat(CreateChatRequest) returns (CreateChatResponse);
  rpc GetUserChats(GetUserChatsRequest) returns (GetUserChatsResponse);
  rpc GetChatById(GetChatByIdRequest) returns (GetChatByIdResponse);
  rpc GetChatMessages(GetChatMessagesRequest) returns (GetChatMessagesResponse);
  rpc MarkMessagesRead(MarkMessagesReadRequest) returns (MarkMessagesReadResponse);
  rpc CheckUserAccessToChat(CheckUserAccessToChatRequest) returns (CheckUserAccessToChatResponse);
}

message Cursor {
  string id = 1;
  google.protobuf.Timestamp created_at = 2;
}

message CreateChatRequest {
  string user_id = 1;
  string other_user_id = 2;
}

message CreateChatResponse {
  string chat_id = 1;
  bool is_new = 2;
}

message GetUserChatsRequest {
  string user_id = 1;
  int32 limit = 2;
  int32 offset = 3;
}

message GetUserChatsResponse {
  repeated Chat chats = 1;
}

message GetChatByIdRequest {
  string id = 1;
}

message GetChatByIdResponse {
  Chat chat = 1;
}

message GetChatMessagesRequest {
  string chat_id = 1;
  int32 limit = 2;
  Cursor cursor = 3;
}

message GetChatMessagesResponse {
  repeated Message messages = 1;
  Cursor next_cursor = 2;
  bool has_more = 3;
}

message MarkMessagesReadRequest {
  string user_id = 1;
  string chat_id = 2;
  repeated string message_ids = 3;
}

message MarkMessagesReadResponse {
  bool success = 1;
}

message CheckUserAccessToChatRequest {
  string chat_id = 1;
  string user_id = 2;
}

message CheckUserAccessToChatResponse {
  bool has_access = 1;
}

message Chat {
  string id = 1;
  string user1_id = 2;
  string user2_id = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  Message last_message = 6;
  int32 unread_count = 7;
}

message Message {
  string id = 1;
  string chat_id = 2;
  string sender_id = 3;
  string content = 4;
  string message_type = 5;  
  repeated Attachment attachments = 6;
  string reply_to = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
  bool is_edited = 10;
  bool is_read = 11;
  google.protobuf.Timestamp read_at = 12;
}

message Attachment {
  string id = 1;
  string url = 2;
  string file_name = 3;
  string mime_type = 4;
  int64 file_size = 5;
  int32 width = 6;     
  int32 height = 7; 
}