// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: post.proto

package postsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostService_CreatePost_FullMethodName               = "/posts.v1.PostService/CreatePost"
	PostService_GetPost_FullMethodName                  = "/posts.v1.PostService/GetPost"
	PostService_UpdatePost_FullMethodName               = "/posts.v1.PostService/UpdatePost"
	PostService_DeletePost_FullMethodName               = "/posts.v1.PostService/DeletePost"
	PostService_RatePost_FullMethodName                 = "/posts.v1.PostService/RatePost"
	PostService_UploadPostImage_FullMethodName          = "/posts.v1.PostService/UploadPostImage"
	PostService_DeletePostImage_FullMethodName          = "/posts.v1.PostService/DeletePostImage"
	PostService_AddInterestingPost_FullMethodName       = "/posts.v1.PostService/AddInterestingPost"
	PostService_RemoveInterestingPost_FullMethodName    = "/posts.v1.PostService/RemoveInterestingPost"
	PostService_GetInterestingUsersCount_FullMethodName = "/posts.v1.PostService/GetInterestingUsersCount"
	PostService_GetUserInterestingPosts_FullMethodName  = "/posts.v1.PostService/GetUserInterestingPosts"
	PostService_ListPosts_FullMethodName                = "/posts.v1.PostService/ListPosts"
	PostService_GetPostRatings_FullMethodName           = "/posts.v1.PostService/GetPostRatings"
)

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostServiceClient interface {
	// CRUD
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	RatePost(ctx context.Context, in *RatePostRequest, opts ...grpc.CallOption) (*RatePostResponse, error)
	UploadPostImage(ctx context.Context, in *UploadPostImageRequest, opts ...grpc.CallOption) (*UploadPostImageResponse, error)
	DeletePostImage(ctx context.Context, in *DeletePostImageRequest, opts ...grpc.CallOption) (*DeletePostImageResponse, error)
	AddInterestingPost(ctx context.Context, in *AddInterestingPostRequest, opts ...grpc.CallOption) (*AddInterestingPostResponse, error)
	RemoveInterestingPost(ctx context.Context, in *RemoveInterestingPostRequest, opts ...grpc.CallOption) (*RemoveInterestingPostResponse, error)
	GetInterestingUsersCount(ctx context.Context, in *GetInterestingUsersCountRequest, opts ...grpc.CallOption) (*GetInterestingUsersCountResponse, error)
	GetUserInterestingPosts(ctx context.Context, in *GetUserInterestingPostsRequest, opts ...grpc.CallOption) (*GetUserInterestingPostsResponse, error)
	// Listing
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	GetPostRatings(ctx context.Context, in *GetPostRatingsRequest, opts ...grpc.CallOption) (*GetPostRatingsResponse, error)
}

type postServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostServiceClient(cc grpc.ClientConnInterface) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, PostService_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, PostService_GetPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, PostService_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, PostService_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) RatePost(ctx context.Context, in *RatePostRequest, opts ...grpc.CallOption) (*RatePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatePostResponse)
	err := c.cc.Invoke(ctx, PostService_RatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UploadPostImage(ctx context.Context, in *UploadPostImageRequest, opts ...grpc.CallOption) (*UploadPostImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPostImageResponse)
	err := c.cc.Invoke(ctx, PostService_UploadPostImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePostImage(ctx context.Context, in *DeletePostImageRequest, opts ...grpc.CallOption) (*DeletePostImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePostImageResponse)
	err := c.cc.Invoke(ctx, PostService_DeletePostImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) AddInterestingPost(ctx context.Context, in *AddInterestingPostRequest, opts ...grpc.CallOption) (*AddInterestingPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddInterestingPostResponse)
	err := c.cc.Invoke(ctx, PostService_AddInterestingPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) RemoveInterestingPost(ctx context.Context, in *RemoveInterestingPostRequest, opts ...grpc.CallOption) (*RemoveInterestingPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveInterestingPostResponse)
	err := c.cc.Invoke(ctx, PostService_RemoveInterestingPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetInterestingUsersCount(ctx context.Context, in *GetInterestingUsersCountRequest, opts ...grpc.CallOption) (*GetInterestingUsersCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterestingUsersCountResponse)
	err := c.cc.Invoke(ctx, PostService_GetInterestingUsersCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetUserInterestingPosts(ctx context.Context, in *GetUserInterestingPostsRequest, opts ...grpc.CallOption) (*GetUserInterestingPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInterestingPostsResponse)
	err := c.cc.Invoke(ctx, PostService_GetUserInterestingPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, PostService_ListPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostRatings(ctx context.Context, in *GetPostRatingsRequest, opts ...grpc.CallOption) (*GetPostRatingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostRatingsResponse)
	err := c.cc.Invoke(ctx, PostService_GetPostRatings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
// All implementations must embed UnimplementedPostServiceServer
// for forward compatibility.
type PostServiceServer interface {
	// CRUD
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	RatePost(context.Context, *RatePostRequest) (*RatePostResponse, error)
	UploadPostImage(context.Context, *UploadPostImageRequest) (*UploadPostImageResponse, error)
	DeletePostImage(context.Context, *DeletePostImageRequest) (*DeletePostImageResponse, error)
	AddInterestingPost(context.Context, *AddInterestingPostRequest) (*AddInterestingPostResponse, error)
	RemoveInterestingPost(context.Context, *RemoveInterestingPostRequest) (*RemoveInterestingPostResponse, error)
	GetInterestingUsersCount(context.Context, *GetInterestingUsersCountRequest) (*GetInterestingUsersCountResponse, error)
	GetUserInterestingPosts(context.Context, *GetUserInterestingPostsRequest) (*GetUserInterestingPostsResponse, error)
	// Listing
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	GetPostRatings(context.Context, *GetPostRatingsRequest) (*GetPostRatingsResponse, error)
	mustEmbedUnimplementedPostServiceServer()
}

// UnimplementedPostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostServiceServer struct{}

func (UnimplementedPostServiceServer) CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedPostServiceServer) GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (UnimplementedPostServiceServer) UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedPostServiceServer) DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedPostServiceServer) RatePost(context.Context, *RatePostRequest) (*RatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RatePost not implemented")
}
func (UnimplementedPostServiceServer) UploadPostImage(context.Context, *UploadPostImageRequest) (*UploadPostImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPostImage not implemented")
}
func (UnimplementedPostServiceServer) DeletePostImage(context.Context, *DeletePostImageRequest) (*DeletePostImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePostImage not implemented")
}
func (UnimplementedPostServiceServer) AddInterestingPost(context.Context, *AddInterestingPostRequest) (*AddInterestingPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInterestingPost not implemented")
}
func (UnimplementedPostServiceServer) RemoveInterestingPost(context.Context, *RemoveInterestingPostRequest) (*RemoveInterestingPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveInterestingPost not implemented")
}
func (UnimplementedPostServiceServer) GetInterestingUsersCount(context.Context, *GetInterestingUsersCountRequest) (*GetInterestingUsersCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterestingUsersCount not implemented")
}
func (UnimplementedPostServiceServer) GetUserInterestingPosts(context.Context, *GetUserInterestingPostsRequest) (*GetUserInterestingPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInterestingPosts not implemented")
}
func (UnimplementedPostServiceServer) ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPosts not implemented")
}
func (UnimplementedPostServiceServer) GetPostRatings(context.Context, *GetPostRatingsRequest) (*GetPostRatingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostRatings not implemented")
}
func (UnimplementedPostServiceServer) mustEmbedUnimplementedPostServiceServer() {}
func (UnimplementedPostServiceServer) testEmbeddedByValue()                     {}

// UnsafePostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostServiceServer will
// result in compilation errors.
type UnsafePostServiceServer interface {
	mustEmbedUnimplementedPostServiceServer()
}

func RegisterPostServiceServer(s grpc.ServiceRegistrar, srv PostServiceServer) {
	// If the following call pancis, it indicates UnimplementedPostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostService_ServiceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_RatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).RatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_RatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).RatePost(ctx, req.(*RatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UploadPostImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPostImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UploadPostImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_UploadPostImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UploadPostImage(ctx, req.(*UploadPostImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePostImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePostImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_DeletePostImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePostImage(ctx, req.(*DeletePostImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_AddInterestingPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInterestingPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).AddInterestingPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_AddInterestingPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).AddInterestingPost(ctx, req.(*AddInterestingPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_RemoveInterestingPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveInterestingPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).RemoveInterestingPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_RemoveInterestingPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).RemoveInterestingPost(ctx, req.(*RemoveInterestingPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetInterestingUsersCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterestingUsersCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetInterestingUsersCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetInterestingUsersCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetInterestingUsersCount(ctx, req.(*GetInterestingUsersCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetUserInterestingPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInterestingPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetUserInterestingPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetUserInterestingPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetUserInterestingPosts(ctx, req.(*GetUserInterestingPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_ListPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRatingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetPostRatings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostRatings(ctx, req.(*GetPostRatingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostService_ServiceDesc is the grpc.ServiceDesc for PostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "posts.v1.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostService_GetPost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostService_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostService_DeletePost_Handler,
		},
		{
			MethodName: "RatePost",
			Handler:    _PostService_RatePost_Handler,
		},
		{
			MethodName: "UploadPostImage",
			Handler:    _PostService_UploadPostImage_Handler,
		},
		{
			MethodName: "DeletePostImage",
			Handler:    _PostService_DeletePostImage_Handler,
		},
		{
			MethodName: "AddInterestingPost",
			Handler:    _PostService_AddInterestingPost_Handler,
		},
		{
			MethodName: "RemoveInterestingPost",
			Handler:    _PostService_RemoveInterestingPost_Handler,
		},
		{
			MethodName: "GetInterestingUsersCount",
			Handler:    _PostService_GetInterestingUsersCount_Handler,
		},
		{
			MethodName: "GetUserInterestingPosts",
			Handler:    _PostService_GetUserInterestingPosts_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _PostService_ListPosts_Handler,
		},
		{
			MethodName: "GetPostRatings",
			Handler:    _PostService_GetPostRatings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
